### ISSUE TITLE
Variants not recognised by Typescript

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#217]
# Bug report

## Describe the bug

When composing styled components variant types aren't getting merged properly and not all of them show up in props

## To Reproduce

1. Go to https://codesandbox.io/s/stitches-ts-issue-forked-kevnu?file=/src/App.tsx
2. Notice that the `rounded` variant doesn't gets recognised as a prop in `IconButton`

## Expected behavior

When composing styled components variants must get deep merged and available as props in the type definition.

**Comment by peduarte** [comment]
@afzalsayed96 thanks for raising this. @jjenzz wonder if you may know what's going on?

**Comment by peduarte** [comment]
@deebov just wondering (still need to do some digging), but do you think this could be a regression of https://github.com/modulz/stitches/pull/166 ?

**Comment by jjenzz** [comment]
Fixed here https://github.com/modulz/stitches/pull/218

**Comment by peduarte** [comment]
I'll do some final testing in canary, then release a new canary release before 0.0.3

**Comment by afzalsayed96** [comment]
I just upgraded the sandbox dependency to v0.03 canary and issue still seems to persist. Perhaps updated types weren't published?

**Comment by peduarte** [comment]
It's because I havent released it yet. I'll leave a comment here when I do, with the version number. You're referring to `0.0.3-canary.0`, that's an old release.

**Comment by peduarte** [comment]
This is fixed in `0.0.3-canary.1`

```bash
yarn install @stitches/react@0.0.3-canary.1`
```

Note, this release contains the following breaking change:
- Util API #209
