### ISSUE TITLE
Global css / double render ?

### ISSUE THREAD

**Issue by Achaak** [modulz/stitches#305]
# Bug report

## Describe the bug
In our project, we have a "blink" when the page load.
The CSS of components is ok when the page is loaded but the global CSS render after.

## To Reproduce
Fresh Next.js typescript project with stitches installed and a font in a head of document

## Expected behavior
We want the page render only when the font is loaded. We tried to change the display parameter in the google font url.

## Screenshots
![image](https://user-images.githubusercontent.com/39270779/98220017-095e0980-1f4e-11eb-89ab-c32c34998404.png)
![image](https://user-images.githubusercontent.com/39270779/98220149-2d214f80-1f4e-11eb-8723-d290eff4b890.png)

## System information

- OS: all
- Browser: all
- Version of Stitches: 0.0.2
- Version of Node.js: 14 / 15

**Comment by peduarte** [comment]
We have fixed some issues with `css.global` in the last few canary releases. 

You can try upgrading to `0.0.3-canary.4` but please note the API has changed slightly:

```jsx
// css.global now returns a function, so assign it to a const
const globalStyles = css.global({})

const App = () => {
  // now call the global function in your top level component
  globalStyles()

  return <div/>
}
```

Please refer to the [releases](https://github.com/modulz/stitches/releases) page for more information.

Let me know if that fixes your issues.

**Comment by Achaak** [comment]
The problem is still present after the version change and modifications.

**Comment by peduarte** [comment]
@Achaak Hmm, not sure then. But I'd be more than happy to take a look at a reproducible example if you can provide one 👀

**Comment by peduarte** [comment]
I'm thinking the flash is coming from the font request and its not something to do with Stitches.

Did you try `&display=swap` in the URL?

Also: https://leerob.io/blog/things-ive-learned-building-nextjs-apps

**Comment by rifaidev** [comment]
@peduarte I think that happens only with SSR, and I'd use your own [Stitches CI: Next.js CodeSandbox](https://codesandbox.io/s/stitches-ci-nextjs-2uwsq) as a reproducible example. _The CodeSandbox is using `0.0.3-canary.3` but same issue happens with `0.0.3-canary.4`_

<img width="1840" alt="Screen Shot 2020-11-09 at 19 27 39" src="https://user-images.githubusercontent.com/4334778/98581521-e458f600-22c1-11eb-999a-f52860f05a8d.png">

**Comment by peduarte** [comment]
@rifaidev we're looking into this 👀 

thank you both

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
