### ISSUE TITLE
fontWeight does not accept tokens

### ISSUE THREAD

**Issue by patrickgdl** [modulz/stitches#319]
# Bug report

## Describe the bug

When trying to use `fontWeight` on `CreateStyled` > `Utils` it only accepts `number` or `lighter, normal or bold` (as expected) but should accept token too to be used with CSS Custom Properties, as it already exposes `FontWeights` for `Tokens`. Typescript gives a type error.

## To Reproduce

Try as below:

```javascript
const theme = {
  fontWeights: {
    $light: "300",
    $regular: "400",
    $medium: "500",
    $semibold: "600",
    $bold: "700",
  },
};

export const { styled, css } = createStyled({
  tokens: theme,
  utils: {
    fontScale: () => (value: keyof typeof theme["fontWeights"] | (number & {})) => ({
      fontWeight: value,
    }),
  },
});;
```

## Expected behavior

Should accept `string` and/or object (`{}`).

## System information

- OS: Windows
- Browser: chrome
- Version of Stitches: 0.0.2
- Version of typescript: 3.9.7

**Comment by peduarte** [comment]
Thanks, will take a look! 👀

**Comment by drenther** [comment]
Seems to work for me in v0.0.3-canary.4

If that helps debug anything.

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.****

**Comment by jylin** [comment]
I think this specific example still doesn't work. With the same above theme setting, this doesn't seem to work.

```
const H1 = styled("h1", {
  fontWeight: "$bold"
}
```
